<?php
global $adb, $table_prefix;

$result = $adb->query("SELECT * FROM {$table_prefix}_language WHERE prefix = 'fr_fr'");
if ($result && $adb->num_rows($result) > 0) {
	$trans = array(
		'Accounts' => array(
			'fr_fr' => array(
				'LBL_NO_PARENT_HIERARCHY'=>'Aucun parent',
			),
		),
		'ALERT_ARR' => array(
			'fr_fr' => array(
				'CONFIRM_EMPTY_FOLDER'=>'Êtes-vous sûr de vouloir vider ce dossier ? Tous les messages seront supprimés.',
				'ERR_TARGET'=>'Aucune cible créée. La liste est vide.',
				'ERR_TARGET_XLS'=>'Aucune donnée exportée. La liste est vide.',
				'GROUPAGE_DUPLICATED'=>'Groupage dupliqué pour le champ : %s',
				'HAS_EXACTLY_ROWS'=>'a exactement',
				'HAS_LESS_ROWS'=>'a moins de',
				'HAS_MORE_ROWS'=>'a plus de',
				'HelpDeskFromMail'=>'VTE à partir du courriel',
				'LBL_ADD_PICKLIST_VALUE'=>'Veuillez faire au moins une nouvelle entrée',
				'LBL_AUTO_TMP_NAME'=>'[AUTO TEMPLATE]',
				'LBL_BACK'=>'Précédent',
				'LBL_CANCEL'=>'Annuler',
				'LBL_CHOOSE_A_REPORT'=>'Choisir un rapport',
				'LBL_CONFIRM_CLOSE_POPUP'=>'Êtes-vous sûr de vouloir fermer la fenêtre ?',
				'LBL_DESCRIPTION'=>'Description',
				'LBL_DISABLE_MODULE'=>'Désactiver le module %s ?',
				'LBL_FILESIZE_EXCEEDS_MAX_UPLOAD_SIZE'=>'Désolé, le fichier téléchargé excède la taille maximale de fichier admise.',
				'LBL_FOLLOW'=>'Me prévenir des changements',
				'LBL_GROUPBY'=>'Regrouper par',
				'LBL_KANBAN_DRAG_HERE'=>'Activer faites glisser ici',
				'LBL_LABEL'=>'Étiquette',
				'LBL_MASS_EDIT_ENQUEUE'=>'Vous avez sélectionné plus que {max_records} articles. Le processus se poursuivra en arrière-plan et vous serez informé à la fin.',
				'LBL_NEW_CONDITION_BUTTON_LABEL'=>'Nouvelle condition',
				'LBL_NO_NETWORK'=>'Aucune connexion réseau disponible.',
				'LBL_NO_RUN_PROCESSES'=>'Aucun processus ne fonctionne',
				'LBL_NO_VALUES_TO_DELETE'=>'Aucune valeur à supprimer',
				'LBL_PLEASE_ADD_COLUMNS'=>'Veuillez ajouter au moins une colonne',
				'LBL_PLEASE_CHOOSE_FIELDNAME'=>'Veuillez donner un nom au champ',
				'LBL_PLEASE_NAME_ALL_COLUMNS'=>'Veuillez donner un nom à toutes les colonnes',
				'LBL_PMH_SELECT_RELATED_TO'=>'Sélectionnez un dossier associé à Process Helper ou désactivez-le',
				'LBL_PM_CHECK_ACTIVE'=>'Le processus n\'est pas encore actif. Souhaitez-vous l\'activer maintenant ?',
				'LBL_PM_ELEMENTS_ACTORS'=>'Participants',
				'LBL_PM_NO_CHECK_SELECTED'=>'Aucune vérification définie',
				'LBL_PM_NO_ENTITY_SELECTED'=>'Aucune entité sélectionnée',
				'LBL_PM_SELECT_ENTITY'=>'Veuillez sélectionner une entité',
				'LBL_PM_SELECT_RESOURCE'=>'Veuillez sélectionner l\'utilisateur',
				'LBL_REMOVE_GROUP_CONDITION'=>'Supprimer le groupe',
				'LBL_REPORT_NAME'=>'Nom du rapport',
				'LBL_ROWS'=>'lignes',
				'LBL_RUN_PROCESSES_ERROR'=>'Erreur lors de l\'exécution du processus',
				'LBL_RUN_PROCESSES_OK'=>'Processus exécuté avec succès',
				'LBL_SEARCH'=>'Recherche',
				'LBL_SELECT_OPTION_DOTDOTDOT'=>'Sélectionner Option...',
				'LBL_SUMMARY'=>'Sommaire',
				'LBL_TABLEFIELD_ALL'=>'Tous',
				'LBL_TABLEFIELD_AT_LEAST_ONE'=>'Au moins un',
				'LBL_TABLEFIELD_AVERAGE'=>'Moyenne',
				'LBL_TABLEFIELD_CURR_VALUE'=>'Actuel',
				'LBL_TABLEFIELD_LAST_VALUE'=>'Dernier',
				'LBL_TABLEFIELD_MAX'=>'Maxi',
				'LBL_TABLEFIELD_MIN'=>'Mini',
				'LBL_TABLEFIELD_SEQUENCE'=>'Séquence',
				'LBL_TABLEFIELD_SUM'=>'Somme',
				'LBL_TODAY'=>'Aujourd\'hui',
				'LBL_UNFOLLOW'=>'Ne pas m\'informer des changements',
				'MISSING_COMPARATOR'=>'Veuillez choisir une condition de comparaison',
				'MODULE_RELATED_TO'=>'Module lié à',
				'NO_ADDRESS_SELECTED'=>'Aucune adresse sélectionnée',
			),
		),
		'APP_STRINGS' => array(
			'fr_fr' => array(
				'AddModuleHomeListView'=>'Nouvel onglet avec liste',
				'AddModuleHomeView'=>'Nouvel onglet de base',
				'AddModuleHomeViewReport'=>'Nouvel onglet avec rapport',
				'DynaForm'=>'Formulaire dynamique',
				'LBL_ACTIVITY_REMINDER_DESCRIPTION'=>'Voici un rappel de l\'activité à venir',
				'LBL_ADD_COLUMN'=>'Ajouter une colonne',
				'LBL_ADD_FIELD_TABLE'=>'Ajouter un champ de table',
				'LBL_ADD_ROW'=>'Ajouter une ligne',
				'LBL_ADD_WIDGET'=>'Ajouter le widget',
				'LBL_ADVANCED'=>'Avancé',
				'LBL_APPOINTMENT_REMINDER'=>'Rappel de rendez-vous',
				'LBL_ATTACH_DOCUMENTS'=>'Joindre des documents',
				'LBL_CHOOSE'=>'Choisir',
				'LBL_CHOOSE_MODHOME_BLOCK_TYPE'=>'Choisir le type de widget',
				'LBL_CHOOSE_WIZARDS'=>'Choisir un ou plusieurs assistants',
				'LBL_COLUMNS'=>'Colonnes',
				'LBL_COLUMN_NAME'=>'Nom de colonne',
				'LBL_CONFIG_PAGE'=>'Configurer la page',
				'LBL_DEFAULT_FILTER'=>'Filtre par défaut',
				'LBL_DELETE_ROW'=>'Supprimer la ligne',
				'LBL_DISMISS'=>'Rejeter',
				'LBL_DISMISS_ALL'=>'Rejeter tout',
				'LBL_DYNAFORM_FORMAT_TYPE_DEFAULT_VALUE'=>'La valeur par défaut doit être insérée dans la syntaxe correcte.',
				'LBL_FIELDS'=>'Champs',
				'LBL_FIELD_TABLE'=>'Champ de table',
				'LBL_FOREACH_ROW'=>'pour chaque ligne',
				'LBL_FROM_HOUR'=>'de',
				'LBL_GLOBAL_SEARCH_STRING'=>'Recherche globale...',
				'LBL_KANBAN_DRAG_DISABLED'=>'Glisser ici désactivé pour cette colonne',
				'LBL_KANBAN_NOT_AVAILABLE'=>'La vue Kanban n\'est pas configurée pour cette vue',
				'LBL_MASSEDIT_ERROR'=>'Quelques erreurs se sont produites pendant MassEdit. {num_fail_records} dossiers n\'ont pas été sauvegardés correctement, sur un total de {num_records} dossiers. Veuillez vérifier les fichiers journaux pour plus de détails.',
				'LBL_MASSEDIT_ERROR_SUBJECT'=>'[VTECRM] MassEdit erreur',
				'LBL_MASSEDIT_OK'=>'MassEdit terminé correctement. {num_records} dossiers ont été modifiés.',
				'LBL_MASSEDIT_OK_DESC'=>'MassEdit pour le module {module} a été terminé correctement.<br>{num_records} dossiers ont été modifiés.',
				'LBL_MASSEDIT_OK_SUBJECT'=>'[VTECRM] MassEdit terminé',
				'LBL_MODHOME_AGGR'=>'Sommaire',
				'LBL_MODHOME_PROC'=>'Processus',
				'LBL_MODHOME_VIS'=>'Aperçu',
				'LBL_NO_AVAILABLE_CHARTS'=>'Aucun graphique disponible pour ce module',
				'LBL_NO_AVAILABLE_FILTERS'=>'Aucun filtre disponible pour ce module',
				'LBL_NO_AVAILABLE_WIZARDS'=>'Aucun assistant disponible',
				'LBL_NO_HOME_BLOCKS'=>'Aucun widget configuré. Cliquez sur %s pour en créer un nouveau',
				'LBL_ON_FIELD'=>'sur le champ',
				'LBL_OPEN'=>'Ouvert',
				'LBL_OVERDUE'=>'En retard de',
				'LBL_PARENT_MODULE'=>'Module parent',
				'LBL_PM_ACTION_FIELD_FORMAT_TYPE'=>'Les valeurs doivent être insérées en utilisant la syntaxe correcte.',
				'LBL_PM_ELEMENTS_ACTORS'=>'Participants',
				'LBL_REMOVE_MODHOME_VIEW'=>'Supprimer l\'onglet',
				'LBL_SNOOZE_ALL'=>'Tout répéter',
				'LBL_TAB_MAIN'=>'Informations',
				'LBL_TAB_RELATED_PRODUCTS'=>'Produits',
				'LBL_TOO_MANY_INPUT_VARS'=>'Certaines variables ont été tronquées. Veuillez augmenter la valeur de max_input_vars dans le fichier php.ini.',
				'LBL_TO_HOUR'=>'à',
				'LBL_WIZARDS'=>'Assistants',
				'NewModuleHomeView'=>'Nouvel onglet',
				'QuickFilter'=>'Filtre rapide',
				'Wizard'=>'Assistant',
				'WIZARD_NEW_OPPORTUNITY'=>'Nouveau potentiel',
				'WIZARD_NEW_TICKET'=>'Nouveau billet',
				'WZ_ChooseAccount'=>'Choisir un compte',
				'WZ_ChooseProduct'=>'Choisir un produit',
				'WZ_ChooseProducts'=>'Choisir des produits',
				'WZ_PotentialData'=>'Champs potentiels',
				'WZ_TicketData'=>'Champs de billet',
				'WZ_UploadDocuments'=>'Télécharger les documents',
			),
		),
		'Assets' => array(
			'fr_fr' => array(
				'Creator'=>'Créateur',
			),
		),
		'Calendar' => array(
			'fr_fr' => array(
				'LBL_ACTIVITY_STATUS'=>'Statut de l\'activité',
				'LBL_TASK_STATUS'=>'État de la tâche',
			),
		),
		'Campaigns' => array(
			'fr_fr' => array(
				'CREATE_TARGET'=>'Créer la cible',
				'EXPORT_LIST'=>'Exporter la liste',
			),
		),
		'ChangeLog' => array(
			'fr_fr' => array(
				'LBL_HAS_CHANGED_THE_RECORD'=>'a modifié le dossier',
				'LBL_HAS_CREATED_THE_RECORD'=>'a créé le dossier',
				'LBL_HAS_LINKED_THE_RECORD'=>'a lié %s',
				'LBL_HAS_REMOVED_LINK_WITH_RECORD'=>'a supprimé le lien avec %s',
			),
		),
		'Charts' => array(
			'fr_fr' => array(
				'Creator'=>'Créateur',
				'LBL_VIEW_REPORT'=>'Afficher le rapport',
				'vtetheme'=>'Thème VTE',
			),
		),
		'CustomView' => array(
			'fr_fr' => array(
				'LBL_KANBAN_ADD_COLUMN'=>'Ajouter une colonne',
				'LBL_KANBAN_ADD_DRAG_ACTION'=>'Ajouter une action',
				'LBL_KANBAN_COLUMNS'=>'NULL',
				'LBL_KANBAN_SETTINGS'=>'Paramètres de kanban',
			),
		),
		'Ddt' => array(
			'fr_fr' => array(
				'Creator'=>'Créateur',
				'LBL_RELATED_PRODUCTS'=>'Détails du produit',
			),
		),
		'Documents' => array(
			'fr_fr' => array(
				'LBL_EDIT_FOLDER'=>'Modifier le dossier',
				'LBL_METADATA'=>'Métadonnées',
				'LBL_SHOW_METADATA'=>'Afficher les métadonnées',
				'LBL_STORAGE_BACKEND'=>'Arrière-plan de stockage',
				'LBL_STORAGE_BACKEND_ALFRESCO'=>'Alfresco',
				'LBL_STORAGE_BACKEND_FILE'=>'Interne',
				'StorageBackend'=>'Arrière-plan de stockage',
			),
		),
		'Emails' => array(
			'fr_fr' => array(
				'LBL_SMTP_ERROR_MULTIPLE'=>'Autres éléments envoyés avec succès.',
			),
		),
		'Geolocalization' => array(
			'fr_fr' => array(
				'Geolocalization'=>'Géolocalisation',
			),
		),
		'HelpDesk' => array(
			'fr_fr' => array(
				'Answer by mail'=>'Répondre par courriel',
				'Answer by mail (info)'=>'Répondre par courriel (infos)',
				'HelpDesk From'=>'VTE à partir du courriel',
				'HelpDesk From Name'=>'VTE à partir du nom',
				'HelpDeskSignature'=>'Signature',
				'LBL_MAIL_INFO'=>'Informations de messagerie',
				'LBL_SIGNATURE_BLOCK'=>'Signature du billet',
				'Mail Bcc'=>'Courriel Cci',
				'Mail Cc'=>'Courriel Cc',
				'Mail Date'=>'Date du courriel',
				'Mail From'=>'Courriel de',
				'Mail To'=>'Courriel à',
				'NO_SIGNATURE_IMAGE'=>'Pas de signature',
			),
		),
		'Import' => array(
			'fr_fr' => array(
				'LBL_CHANGE_ENCODING'=>'Changer l\'encodage',
				'LBL_DETECTED_ENCODING'=>'Détecter l\'encodage',
				'LBL_IMPORT_FORMAT'=>'Format',
			),
		),
		'Messages' => array(
			'fr_fr' => array(
				'Draft'=>'Brouillon',
				'ERR_IMAP_AUTENTICATION'=>'Échec de la connexion',
				'LBL_DOWNLOAD_TNEF'=>'Télécharger les pièces jointes contenues',
				'LBL_IMAP_SEARCH_ERROR_1'=>'Intervalle de recherche non défini',
				'LBL_IMAP_SEARCH_ERROR_2'=>'Condition de recherche non définie',
				'LBL_IMAP_SEARCH_ERROR_3'=>'Condition de recherche non définie',
				'LBL_IMAP_SEARCH_ERROR_4'=>'Certaines conditions de recherche ne sont pas prises en charge par imap.',
				'LBL_NO_RESULT_TILL'=>'Aucun résultat jusqu\'à %s',
				'LBL_SEARCH_MORE'=>'Rechercher plus',
				'LBL_SEARCH_TILL'=>'Chercher jusqu\'à %s',
				'LBL_SMTP_SERVER'=>'Serveur SMTP',
				'LBL_USE_SMTP'=>'Utiliser le serveur SMTP',
			),
		),
		'ModNotifications' => array(
			'fr_fr' => array(
				'LBL_UNFOLLOW'=>'Ne pas m\'informer des changements',
			),
		),
		'Myfiles' => array(
			'fr_fr' => array(
				'StorageBackend'=>'Arrière-plan de stockage',
			),
		),
		'Newsletter' => array(
			'fr_fr' => array(
				'Creator'=>'Créateur',
				'Failed'=>'Échec',
				'LBL_ATTEMPTS_EXHAUSTED'=>'Tentatives épuisées',
				'LBL_AUTO_TMP_NAME'=>'[AUTO TEMPLATE]',
				'LBL_TEMPLATE_PREVIEW'=>'Aperçu du modèle',
				'Sent'=>'Envoyé',
			),
		),
		'Processes' => array(
			'fr_fr' => array(
				'Actor'=>'Participant',
				'Assigned To'=>'Attribué à',
				'Created Time'=>'Temps créé',
				'Description'=>'Description',
				'Ended'=>'NULL',
				'Expiration'=>'Expiration',
				'Father process'=>'Processus père',
				'LBL_CHANGE_POSITION'=>'Position de force',
				'LBL_CONDITION_ON'=>'Vérifier',
				'LBL_CONDITION_ON_MODULE'=>'Vérifier le module %s.',
				'LBL_CONTINUE_EXECUTION'=>'Poursuivre l\'exécution',
				'LBL_CUSTOM_INFORMATION'=>'Informations personnalisées',
				'LBL_DESCRIPTION_INFORMATION'=>'Informations de description',
				'LBL_EXECUTION_CONDITION'=>'Exécuter la vérification %s',
				'LBL_EXECUTION_SUBPROCESS'=>'Exécuter le processus',
				'LBL_FUTURE_ACTION'=>'devra effectuer l\'action :',
				'LBL_LOG_END_ACTIVITY'=>'mettre fin à l\'activité',
				'LBL_LOG_START_ACTIVITY'=>'passé dans cette activité à partir de',
				'LBL_MANUAL_CHANGED_POSITION'=>'Position modifiée manuellement',
				'LBL_PAST_ACTION'=>'a exécuté l\'action :',
				'LBL_PROCESSES_INFORMATION'=>'Informations de processus',
				'LBL_RUN_PROCESS'=>'Continuer le processus',
				'LBL_RUN_PROCESSES'=>'Continuer le processus',
				'LBL_SAVE_AND_RUN_PROCESSES_BUTTON_LABEL'=>'Enregistrer et exécuter',
				'LBL_SAVE_AND_RUN_PROCESSES_BUTTON_TITLE'=>'Enregistrer et exécuter les processus',
				'LBL_SELECT_ACTOR'=>'Sélectionner l\'acteur',
				'LBL_TABLEFIELD_AVERAGE'=>'Médias',
				'LBL_TABLEFIELD_CYCLE_CURR_VALUE'=>'Actuel',
				'LBL_TABLEFIELD_LAST_VALUE'=>'Dernier',
				'LBL_TABLEFIELD_MAX'=>'Maximum',
				'LBL_TABLEFIELD_MIN'=>'Minimum',
				'LBL_TABLEFIELD_SEQUENCE'=>'Séquence',
				'LBL_TABLEFIELD_SUM'=>'Somme',
				'Modified Time'=>'Temps modifié',
				'Process Graph'=>'Graphique du processus',
				'Process Name'=>'Nom du processus',
				'Processes'=>'Processus',
				'Processes Children'=>'Processus enfants',
				'Related to'=>'Associés à',
				'Requested action'=>'Action demandée',
				'Running'=>'NULL',
				'SINGLE_Processes'=>'Processus',
				'Status'=>'NULL',
				'Waiting'=>'NULL',
			),
		),
		'ProjectMilestone' => array(
			'fr_fr' => array(
				'Creator'=>'Créateur',
			),
		),
		'ProjectPlan' => array(
			'fr_fr' => array(
				'Creator'=>'Créateur',
			),
		),
		'ProjectTask' => array(
			'fr_fr' => array(
				'Calculate working days'=>'Calcul automatique de la durée prévue',
				'Creator'=>'Créateur',
				'Working days'=>'Durée prévue',
			),
		),
		'Reports' => array(
			'fr_fr' => array(
				'LBL_ADD_CHART_TO_REPORT'=>'Ajouter un graphique au rapport',
				'LBL_ADD_CLUSTER'=>'Ajouter un groupe',
				'LBL_CHART_NEEDS_SUMMARY'=>'Pour créer un graphique, vous devez créer un rapport de synthèse',
				'LBL_CLUSTERS'=>'Groupes de haut en bas',
				'LBL_CLUSTERS_LIST'=>'Groupes actifs',
				'LBL_CLUSTER_COLOR'=>'Couleur du graphique',
				'LBL_CLUSTER_FILTER_DESC'=>'Sélectionner les filtres pour l\'extraction du groupe',
				'LBL_CLUSTER_NAME'=>'Nom du groupe',
				'LBL_COMPARE_WITH_FIELD'=>'Comparer avec un autre champ',
				'LBL_EDIT_CLUSTER'=>'Modifier le groupe',
				'LBL_FIELD_FOR_SUMMARY'=>'Groupe',
				'LBL_FORMULA'=>'Formule',
				'LBL_GROUP_BY_FIELD'=>'Regrouper par ce champ',
				'LBL_ORDER_OF_SELECTED_FIELDS'=>'Ordre des champs sélectionnés',
				'LBL_SELECT_CLUSTERS'=>'Sélectionner les groupes dans lesquels diviser le rapport',
				'LBL_STDFILTER_EDITABLE'=>'Ce filtre sera modifiable directement depuis la page de rapport',
				'LBL_TEMPORAL_FILTER'=>'Filtre temporel',
				'LBL_USE_THE_FIELDS_OF'=>'Utiliser les champs de',
				'LBL_WANT_TO_CREATE_CHART'=>'Souhaitez-vous créer un graphique pour ce rapport ?',
				'MODULE_RELATED_TO'=>'Module lié à',
				'This Month Tasks'=>'Tâches de ce mois-ci',
			),
		),
		'ServiceContracts' => array(
			'fr_fr' => array(
				'Creator'=>'Créateur',
			),
		),
		'Services' => array(
			'fr_fr' => array(
				'Creator'=>'Créateur',
			),
		),
		'Settings' => array(
			'fr_fr' => array(
				'LBL_ADD_RELATEDLIST'=>'Ajouter RelatedList',
				'LBL_ADD_TAB'=>'Ajouter un onglet',
				'LBL_CHOOSE_TRANSFER_TAB'=>'Où souhaitez-vous déplacer les blocs de cet onglet ?',
				'LBL_CHOOSE_TRANSFER_TAB_BLOCK'=>'Où souhaitez-vous déplacer ce bloc ?',
				'LBL_CREATE_NEW_CAMPAIGN'=>'Créer un nouveau à chaque fois',
				'LBL_DIMPORT_FORMAT_NUMBER'=>'Numérique',
				'LBL_DOWNLOAD_BPMN'=>'Télécharger BPMN',
				'LBL_DOWNLOAD_VTEBPMN'=>'Télécharger VTE BPMN',
				'LBL_DO_NOTHING'=>'Ne rien faire',
				'LBL_DO_NOT_IMPORT_ANYMORE'=>'Ne pas importer plus',
				'LBL_EDIT_TAB'=>'Modifier l\'onglet',
				'LBL_EVERY_TIME_TIME_CONDITION_TRUE'=>'chaque fois que la condition est vraie',
				'LBL_EXCLUSIVEGATEWAY_OTHER'=>'autrement passer à',
				'LBL_EXCLUSIVEGATEWAY_SUCCESS'=>'Si la condition précédente est satisfaite aller à',
				'LBL_FIELD_BUTTON'=>'Bouton',
				'LBL_FIELD_BUTTON_CODE'=>'Code',
				'LBL_FIELD_BUTTON_ONCLICK'=>'On click',
				'LBL_FORCE_CHECK_RELATED_TO'=>'Vérification de force pour Related To',
				'LBL_FPOFV_CURRENT_VALUE'=>'Valeur actuelle',
				'LBL_FROM_PROCESS'=>'À partir du processus',
				'LBL_IMPORT_BPMN'=>'Importer BPMN',
				'LBL_IMPORT_LINKKEY_KEYFIELD'=>'Vous devez d\'abord sélectionner un champ clé',
				'LBL_IMPORT_VTEBPMN'=>'Importer VTE BPMN',
				'LBL_INSERT_ON_TABLE_FIELD'=>'Insérer une ligne dans',
				'LBL_MAILCONV_MATCH_FIELD'=>'Champ de concordance',
				'LBL_MAILCONV_MATCH_FIELD_CRMID'=>'Id Billet',
				'LBL_MAIN_MODULE_DESC'=>'Le module à créer avec cet assistant',
				'LBL_MANAGE_RELATEDLIST'=>'Gérer RelatedList',
				'LBL_MODULENAME_NOT_ALLOWED'=>'Le nom du module n\'est pas autorisé, veuillez choisir un autre nom.',
				'LBL_MOVE_BLOCK'=>'Déplacer le bloc',
				'LBL_MOVE_TO_ANOTHER_TAB'=>'Déplacer à un autre onglet',
				'LBL_NONE_DYNAFORM_CONDITIONAL'=>'Aucun formulaire dynamique configuré',
				'LBL_ON_MANUAL_MODE'=>'lorsque vous cliquez sur le bouton Run',
				'LBL_ON_SUBPROCESS'=>'lorsque le sous-processus est exécuté',
				'LBL_OVERWRITE_MESSAGE'=>'Remplacer tout le corps du message',
				'LBL_PARENT_MODULE_DESC'=>'Choisir le module de départ (facultatif)',
				'LBL_PMH_CURRENT_ENTITY'=>'Entité actuelle',
				'LBL_PMH_DESCRIPTION'=>'Instructions',
				'LBL_PMH_RELATEDTO'=>'Associés à',
				'LBL_PMH_RELATED_TO_POPUP'=>'Afficher la fenêtre dans l\'entité associée',
				'LBL_PMH_RELATED_TO_POPUP_EVERYTIME'=>'Jusqu\'à ce que la condition soit vérifiée',
				'LBL_PMH_RELATED_TO_POPUP_ONCE'=>'Seulement la première fois',
				'LBL_PM_ACTION'=>'Action',
				'LBL_PM_ACTIONS'=>'Actions',
				'LBL_PM_ACTION_Create'=>'Créer l\'entité',
				'LBL_PM_ACTION_Cycle'=>'Cycle',
				'LBL_PM_ACTION_Delete'=>'Supprimer l\'entité',
				'LBL_PM_ACTION_DeleteConditionals'=>'Réinitialiser les champs conditionnels',
				'LBL_PM_ACTION_DeleteTableRow'=>'Supprimer la ligne de la table',
				'LBL_PM_ACTION_DELETETABLEROW_INFO'=>'Supprimer les lignes qui satisfont la condition. S\'il n\'y a pas de condition toutes les lignes seront supprimées.',
				'LBL_PM_ACTION_Email'=>'Envoyer un courriel',
				'LBL_PM_ACTION_InsertTableRow'=>'Insérer une ligne de tableau',
				'LBL_PM_ACTION_Relate'=>'Lier les entités',
				'LBL_PM_ACTION_ResetDynaform'=>'Réinitialiser le formulaire dynamique',
				'LBL_PM_ACTION_SendNewsletter'=>'Envoyer le bulletin d\'informations',
				'LBL_PM_ACTION_TITLE'=>'Titre de l\'action',
				'LBL_PM_ACTION_Update'=>'Mettre à jour l\'entité',
				'LBL_PM_ADVANCED_ACTIONS'=>'Avancé',
				'LBL_PM_ADVANCED_FIELD_ASSIGNMENT'=>'Affectation avancée',
				'LBL_PM_ADVANCED_PERMISSIONS'=>'Autorisations avancées',
				'LBL_PM_ADVANCED_PERMISSIONS_VISIBILITY'=>'Visibilité',
				'LBL_PM_ADVANCED_PERMISSIONS_WIDGET'=>'Participants',
				'LBL_PM_AFTER'=>'Si le processus est encore dans cet état pendant plus de',
				'LBL_PM_CHECK_TIMER_START_DATE'=>'Il n\'est pas permis de définir un temps passé dans la minuterie de démarrage',
				'LBL_PM_CHECK_TIMER_START_GREATER_THAN_END'=>'L\'heure de fin doit être supérieure à l\'heure de début',
				'LBL_PM_CONDITIONALS'=>'Conditionnelles',
				'LBL_PM_CREATE_ACTION'=>'Nouvelle action',
				'LBL_PM_CREATE_ACTION_OF_TYPE'=>'Créer une nouvelle action',
				'LBL_PM_CRON_VALUE_SELECTED'=>'Récurrence sélectionnée',
				'LBL_PM_DYNAFORM_CONDITIONALS'=>'Conditionnelles sur le formulaire dynamique',
				'LBL_PM_ENABLE_RECURRENCE'=>'Activer la récurrence',
				'LBL_PM_FIELD_GO_BACK'=>'Retour aux options',
				'LBL_PM_GATEWAY_END_PARALLEL'=>'Choisir la passerelle de fermeture parallèle',
				'LBL_PM_GATEWAY_NO_CONDITIONS'=>'Aucune condition configurée à l\'étape précédente.',
				'LBL_PM_GO_TO_NEXT_STEP'=>'continuer',
				'LBL_PM_IMPORT_BLOCK'=>'Importer le bloc',
				'LBL_PM_IMPORT_BLOCKS_TITLE'=>'Importer les blocs des autres formulaires dynamiques',
				'LBL_PM_LIMIT_EXCEEDED'=>'Vous devez activer les fonctionnalités supplémentaires afin d\'utiliser plus de %s processus.',
				'LBL_PM_LOGS'=>'Journaux',
				'LBL_PM_MANAGE_DYNAFORM'=>'Gérer le formulaire dynamique',
				'LBL_PM_MODELER'=>'Diagramme',
				'LBL_PM_NO_ACTIONS'=>'Aucune action configurée',
				'LBL_PM_NO_RULES'=>'Pas de règles configurées',
				'LBL_PM_PARTECIPANT_OF'=>'Participant de',
				'LBL_PM_PREVIEW_RECURRENCE'=>'Aperçu des récurrences',
				'LBL_PM_RESOURCE'=>'Participant',
				'LBL_PM_RULE'=>'Règle',
				'LBL_PM_SAVE_DIAGRAM_ERROR'=>'Échec de l\'enregistrement du diagramme',
				'LBL_PM_SDK_CUSTOM_FUNCTION'=>'Fonction SDK',
				'LBL_PM_SDK_CUSTOM_FUNCTIONS'=>'Fonctions SDK',
				'LBL_PM_SDK_PARAMS'=>'Paramètres SDK',
				'LBL_PM_SELECT_OPTION_FIELD'=>'Sélectionner le champ...',
				'LBL_PM_START_EVENT_NOTE'=>'Configurer les conditions temporelles et définir l\'indicateur actif du Process Maker afin de planifier le processus. Il suffit de changer les paramètres suivants pour le planifier à nouveau.',
				'LBL_PM_SUBPROCESSES'=>'Sous-processus',
				'LBL_PM_TO_GO_TO_NEXT_STEP'=>'pour aller',
				'LBL_PM_WAIT'=>'Patienter',
				'LBL_PRESENCE_AND_ORDERING'=>'Visibilité et passer commande',
				'LBL_PROCESS_HELPER'=>'Process Helper',
				'LBL_PROCESS_MAKER'=>'Gestionnaire de processus',
				'LBL_PROCESS_MAKER_ALERT_EMPTY_BPMN'=>'Sélectionnez le fichier à télécharger ou collez le code',
				'LBL_PROCESS_MAKER_DESC'=>'Permet de créer des processus personnalisés',
				'LBL_PROCESS_MAKER_MANAGE_OTHER_RECORD'=>'Utilisez d\'autres dossiers dans le processus',
				'LBL_PROCESS_MAKER_PASTE_CODE'=>'ou cliquez ici, puis collez le code',
				'LBL_PROCESS_MAKER_RECORD_DESC'=>'Description',
				'LBL_PROCESS_MAKER_RECORD_NAME'=>'Nom',
				'LBL_PROCESS_MAKER_REQUIRED_TO_GO'=>'Obligatoire pour aller',
				'LBL_PROCESS_MAKER_REQUIRED_TO_GO_ALL'=>'Attendez toutes les réponses pour poursuivre',
				'LBL_RELATIONS_DESC'=>'Choisissez les autres modules liés',
				'LBL_RESCAN_FOLDERS'=>'y compris les messages passés ignorés',
				'LBL_REUSE_CAMPAIGN'=>'Créer et réutiliser ensuite la même campagne',
				'LBL_SELECT_FROM_PROCESS'=>'Sélectionner dans le processus',
				'LBL_SELECT_STATIC'=>'Sélectionner le dossier statique',
				'LBL_SORT_BY_COUNT'=>'Trier par nombre',
				'LBL_TAB_NAME'=>'Nom de l\'onglet',
				'LBL_UPLOAD_FILE_BPMN'=>'Sélectionner le fichier',
				'LBL_USE_SIGNATURE'=>'Utiliser la signature de l\'utilisateur',
				'LBL_WHEN_TO_RUN_PM_TASK'=>'Quand exécuter la vérification',
				'LBL_WIZARDLABEL'=>'Nom de l\'Assistant',
				'LBL_WIZARDLABEL_DESC'=>'Choisissez un nom pour cet assistant, par exemple : \Create Account\""',
				'LBL_WIZARD_MAKER'=>'Créateur d\'assistant',
				'LBL_WIZARD_MAKER_STEP1'=>'Informations sur l\'assistant',
				'LBL_WIZARD_MAKER_STEP2'=>'Module principal',
				'LBL_WIZARD_MAKER_STEP3'=>'Champs',
				'LBL_WIZARD_MAKER_STEP4'=>'Relations',
				'LBL_WMAKER_STEP1_INTRO'=>'Choisir le module parent et le nom de l\'Assistant',
				'LBL_WMAKER_STEP3_INTRO'=>'Choisir les champs de l\'assistant',
			),
		),
		'Targets' => array(
			'fr_fr' => array(
				'Creator'=>'Créateur',
				'Included Targets'=>'Cibles incluses',
				'Parent Targets'=>'Cibles parent',
			),
		),
		'Timecards' => array(
			'fr_fr' => array(
				'Creator'=>'Créateur',
			),
		),
		'Users' => array(
			'fr_fr' => array(
				'LBL_LOGOUT_REASON_CONCURRENT'=>'On a décelé une autre connexion avec votre nom d\'utilisateur et le nombre maximal de sessions simultanées autorisées a été atteint.',
				'LBL_LOGOUT_REASON_EXPIRED'=>'La session a expiré, veuillez vous connecter à nouveau.',
				'LBL_SELECT_ALL_USER'=>'Utilisateur sans filtre d\'autorisations',
				'LBL_SELECT_CUSTOM_USER'=>'Utilisateur de la liste filtrée',
			),
		),
		'Visitreport' => array(
			'fr_fr' => array(
				'Altro'=>'Autres',
				'Analisi scientifiche'=>'Analyse scientifique',
				'Campioni'=>'Échantillons',
				'Conoscenza'=>'Contact',
				'Consegna'=>'Livraison',
				'Consegna Offerta'=>'Offre de livraison',
				'Consulenza'=>'Conseils',
				'Controllo avanzamento'=>'Contrôle de progression',
				'Offerta'=>'Offre',
				'Presentazione'=>'Présentation',
				'Presentazione Prodotti'=>'Présentation des produits',
				'Prodotti'=>'Produits',
				'Ritiro offerta'=>'Offre de retrait',
				'Stesura capitolato'=>'Rédaction de spécifications',
				'Voci di capitolato'=>'Éléments de spécifications',
			),
		),
	);
	foreach ($trans as $module=>$modlang) {
		foreach ($modlang as $lang=>$translist) {
			foreach ($translist as $label=>$translabel) {
				SDK::setLanguageEntry($module, $lang, $label, $translabel);
			}
		}
	}
}